# Generated by Django 6.0.5 on 2026-05-22 14:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Firm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('source_type', models.CharField(choices=[('direct_company', 'Direct Company'), ('distributor', 'Distributor Company'), ('stockist', 'Stockist Company'), ('local_market', 'Open / Local Market')], max_length=30)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('address', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_number', models.CharField(max_length=100)),
                ('bill_date', models.DateField(default=django.utils.timezone.now)),
                ('bill_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('previous_debt_at_bill_time', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='ledger.firm')),
            ],
            options={
                'ordering': ['-bill_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(default=django.utils.timezone.now)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank'), ('other', 'Other')], default='cash', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='ledger.bill')),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='ledger.firm')),
            ],
            options={
                'ordering': ['-payment_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('bill_created', 'Bill Created'), ('payment_made', 'Payment Made'), ('adjustment', 'Adjustment')], max_length=30)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('increase', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('decrease', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='ledger.bill')),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='ledger.firm')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='ledger.payment')),
            ],
            options={
                'ordering': ['date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Representative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='representatives', to='ledger.firm')),
            ],
        ),
        migrations.AddField(
            model_name='payment',
            name='representative',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='ledger.representative'),
        ),
        migrations.AddField(
            model_name='bill',
            name='representative',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bills', to='ledger.representative'),
        ),
    ]
