# Generated by Django 6.0.5 on 2026-05-22 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledgerentry',
            name='entry_type',
            field=models.CharField(choices=[('opening_balance', 'Opening Balance'), ('bill_created', 'Bill Created'), ('payment_made', 'Payment Made'), ('adjustment', 'Adjustment')], max_length=30),
        ),
    ]
