# Generated by Django 6.0.5 on 2026-05-30 13:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0002_alter_ledgerentry_entry_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='representative',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
