# Generated by Django 6.0.5 on 2026-06-06 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0003_representative_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledgerentry',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='When this entry was soft deleted', null=True),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Soft delete flag'),
        ),
    ]
