# Generated by Django 6.0.3 on 2026-06-10 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0004_ledgerentry_deleted_at_ledgerentry_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='firm',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='When this firm was soft deleted', null=True),
        ),
        migrations.AddField(
            model_name='firm',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Soft delete flag'),
        ),
        migrations.AddField(
            model_name='representative',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='When this representative was soft deleted', null=True),
        ),
        migrations.AddField(
            model_name='representative',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Soft delete flag'),
        ),
    ]
