# Generated by Django 6.0.5 on 2026-10-01 07:58

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


def batch_existing_ledger_entries(apps, schema_editor):
    LedgerEntry = apps.get_model("ledger", "LedgerEntry")
    TransactionBatch = apps.get_model("ledger", "TransactionBatch")
    balances = {}
    database = schema_editor.connection.alias

    for entry in LedgerEntry.objects.using(database).order_by("date", "id").iterator():
        previous = balances.get(entry.firm_id, 0)
        delta = 0 if entry.is_deleted else entry.increase - entry.decrease
        after = previous + delta
        batch = TransactionBatch.objects.using(database).create(
            firm_id=entry.firm_id,
            date=entry.date,
            previous_balance=previous,
            balance_after=after,
        )
        LedgerEntry.objects.using(database).filter(pk=entry.pk).update(transaction_batch_id=batch.pk)
        balances[entry.firm_id] = after


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0005_firm_deleted_at_firm_is_deleted_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='firm',
            name='balance_version',
            field=models.PositiveBigIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='entry_type',
            field=models.CharField(choices=[('opening_balance', 'Opening Balance'), ('bill_created', 'Bill Created'), ('payment_made', 'Payment Made'), ('adjustment', 'Adjustment'), ('reversal', 'Reversal'), ('restoration', 'Restoration')], max_length=30),
        ),
        migrations.CreateModel(
            name='TransactionBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('payload_hash', models.CharField(blank=True, default='', max_length=64)),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('previous_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('balance_after', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('kind', models.CharField(choices=[('transaction', 'Transaction'), ('reversal', 'Reversal'), ('restoration', 'Restoration')], default='transaction', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('reversed', 'Reversed')], default='active', max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pharmacy_transaction_batches', to=settings.AUTH_USER_MODEL)),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transaction_batches', to='ledger.firm')),
                ('original_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_events', to='ledger.transactionbatch')),
            ],
            options={
                'ordering': ['date', 'id'],
            },
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='transaction_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='ledger.transactionbatch'),
        ),
        migrations.RunPython(batch_existing_ledger_entries, migrations.RunPython.noop),
    ]
