# Generated by Django 6.0.8 on 2026-10-01 21:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def backfill_deletion_metadata(apps, schema_editor):
    database = schema_editor.connection.alias
    Bill = apps.get_model("ledger", "Bill")
    Entry = apps.get_model("ledger", "LedgerEntry")
    Batch = apps.get_model("ledger", "TransactionBatch")
    Group = apps.get_model("ledger", "DeletionGroup")
    Member = apps.get_model("ledger", "DeletionMember")
    for bill in Bill.objects.using(database).all().iterator():
        entry = Entry.objects.using(database).filter(
            bill_id=bill.pk, entry_type="bill_created", transaction_batch__kind="transaction",
        ).order_by("id").first()
        if entry:
            Bill.objects.using(database).filter(pk=bill.pk).update(creation_batch_id=entry.transaction_batch_id)
    for root in Batch.objects.using(database).filter(kind="transaction", status="reversed").iterator():
        reversal = Batch.objects.using(database).filter(
            original_batch_id=root.pk, kind="reversal",
        ).order_by("-created_at", "-id").first()
        if reversal is None:
            continue  # Without an offset there is no safe financial recovery to replay.
        group = Group.objects.using(database).create(
            firm_id=root.firm_id, deleted_at=reversal.created_at,
            created_by_id=reversal.created_by_id, reason=reversal.reason[:500],
        )
        Member.objects.using(database).create(group_id=group.pk, batch_id=root.pk, reversal_id=reversal.pk)
        Batch.objects.using(database).filter(pk=root.pk).update(deletion_group_id=group.pk)


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0006_transaction_batches_and_balance_lock'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='creation_batch',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_bills', to='ledger.transactionbatch'),
        ),
        migrations.CreateModel(
            name='DeletionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('transaction', 'Transaction'), ('bill', 'Bill and linked payments')], default='transaction', max_length=20)),
                ('deleted_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('reason', models.CharField(max_length=500)),
                ('bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ledger.bill')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ledger.firm')),
            ],
        ),
        migrations.AddField(
            model_name='transactionbatch',
            name='deletion_group',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deleted_batches', to='ledger.deletiongroup'),
        ),
        migrations.CreateModel(
            name='DeletionMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deletion_memberships', to='ledger.transactionbatch')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='ledger.deletiongroup')),
                ('reversal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deletion_offsets', to='ledger.transactionbatch')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('group', 'batch'), name='unique_deletion_member')],
            },
        ),
        migrations.RunPython(backfill_deletion_metadata, migrations.RunPython.noop),
    ]
