# Generated by Django 6.0.8 on 2026-10-02 20:00

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
from ._integrity_preflight import verify


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0007_timed_deletion_groups'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(verify, migrations.RunPython.noop),
        migrations.CreateModel(
            name='BillEditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('before', models.JSONField()),
                ('after', models.JSONField()),
            ],
        ),
        migrations.AddField(
            model_name='transactionbatch',
            name='posting_receipt',
            field=models.JSONField(blank=True, editable=False, null=True),
        ),
        migrations.AddConstraint(
            model_name='bill',
            constraint=models.CheckConstraint(condition=models.Q(('bill_amount__gt', 0), ('bill_amount__lte', Decimal('9999999999.99'))), name='bill_positive_supported_amount'),
        ),
        migrations.AddConstraint(
            model_name='ledgerentry',
            constraint=models.CheckConstraint(condition=models.Q(('decrease__gte', 0), ('decrease__lte', Decimal('9999999999.99')), ('increase__gte', 0), ('increase__lte', Decimal('9999999999.99'))), name='ledger_nonnegative_supported_amounts'),
        ),
        migrations.AddConstraint(
            model_name='ledgerentry',
            constraint=models.CheckConstraint(condition=models.Q(('increase', 0), ('decrease', 0), _connector='OR'), name='ledger_one_money_side'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0), ('amount__lte', Decimal('9999999999.99'))), name='payment_positive_supported_amount'),
        ),
        migrations.AddField(
            model_name='billeditevent',
            name='actor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='billeditevent',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='edit_events', to='ledger.transactionbatch'),
        ),
        migrations.AddField(
            model_name='billeditevent',
            name='bill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ledger.bill'),
        ),
    ]
