# Generated by Django 6.0.8 on 2026-10-02 20:04

import django.db.models.functions.math
import django.db.models.lookups
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0008_ledger_integrity'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='bill',
            constraint=models.CheckConstraint(condition=django.db.models.lookups.Exact(django.db.models.functions.math.Round('bill_amount', 2), models.F('bill_amount')), name='bill_exact_cents'),
        ),
        migrations.AddConstraint(
            model_name='ledgerentry',
            constraint=models.CheckConstraint(condition=models.Q(django.db.models.lookups.Exact(django.db.models.functions.math.Round('increase', 2), models.F('increase')), django.db.models.lookups.Exact(django.db.models.functions.math.Round('decrease', 2), models.F('decrease'))), name='ledger_exact_cents'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=django.db.models.lookups.Exact(django.db.models.functions.math.Round('amount', 2), models.F('amount')), name='payment_exact_cents'),
        ),
    ]
