# Generated by Django 6.0.8 on 2026-10-02 20:16

import django.db.models.functions.math
import django.db.models.lookups
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0009_exact_cent_constraints'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='bill',
            constraint=models.CheckConstraint(condition=models.Q(('previous_debt_at_bill_time__gte', Decimal('-9999999999.99')), ('previous_debt_at_bill_time__lte', Decimal('9999999999.99')), django.db.models.lookups.Exact(django.db.models.functions.math.Round('previous_debt_at_bill_time', 2), models.F('previous_debt_at_bill_time'))), name='bill_supported_snapshot'),
        ),
        migrations.AddConstraint(
            model_name='transactionbatch',
            constraint=models.CheckConstraint(condition=models.Q(('balance_after__gte', Decimal('-9999999999.99')), ('balance_after__lte', Decimal('9999999999.99')), ('previous_balance__gte', Decimal('-9999999999.99')), ('previous_balance__lte', Decimal('9999999999.99'))), name='batch_supported_balances'),
        ),
        migrations.AddConstraint(
            model_name='transactionbatch',
            constraint=models.CheckConstraint(condition=models.Q(django.db.models.lookups.Exact(django.db.models.functions.math.Round('previous_balance', 2), models.F('previous_balance')), django.db.models.lookups.Exact(django.db.models.functions.math.Round('balance_after', 2), models.F('balance_after'))), name='batch_exact_cent_balances'),
        ),
    ]
