# Generated by Django 6.0.8 on 2026-10-02 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0010_snapshot_bounds'),
    ]

    operations = [
        migrations.AddField(
            model_name='billeditevent',
            name='actor_snapshot',
            field=models.JSONField(editable=False, null=True),
        ),
    ]
