# Generated by Django 6.0.8 on 2026-10-03 21:15

import django.db.models.deletion
import django.db.models.functions.math
import django.db.models.lookups
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0011_immutable_actor_identity'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='is_disabled',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='bill',
            name='bill_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='entry_type',
            field=models.CharField(choices=[('opening_balance', 'Opening Balance'), ('bill_created', 'Bill Created'), ('payment_made', 'Payment Made'), ('adjustment', 'Adjustment'), ('reversal', 'Reversal'), ('restoration', 'Restoration'), ('carry_forward', 'Debt Carry Forward'), ('transfer_undo', 'Undo Debt Carry Forward')], max_length=30),
        ),
        migrations.AlterField(
            model_name='transactionbatch',
            name='kind',
            field=models.CharField(choices=[('transaction', 'Transaction'), ('reversal', 'Reversal'), ('restoration', 'Restoration'), ('carry_forward', 'Debt Carry Forward'), ('transfer_undo', 'Undo Debt Carry Forward')], default='transaction', max_length=20),
        ),
        migrations.CreateModel(
            name='BillCarryForward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('receipt', models.JSONField(editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='carry_forward', to='ledger.transactionbatch')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transfers', to='ledger.bill')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_transfers', to='ledger.bill')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('source', models.F('destination')), _negated=True), name='transfer_different_bills'), models.CheckConstraint(condition=models.Q(('amount__gte', 0), ('amount__lte', Decimal('9999999999.99')), django.db.models.lookups.Exact(django.db.models.functions.math.Round('amount', 2), models.F('amount'))), name='transfer_supported_exact_amount')],
            },
        ),
    ]
